import { print, printRev } from "./ibh/printNumber.js";
import { sort } from "./ibh/Sort.js";
import { printSteps } from "./ibh/towerOfHonoi.js";
import { multiply } from "./ibh/multipy.js";
import { generateGrammar } from "./ibh/kthSymbol.js";
import Stack from "./datastructure/Stack.js";
import { deleteMiddle, reverse, sortStack } from "./ibh/stackOperation.js";

console.log(" =*=*=*=*= IBH Method =*=*=*=*= ");
console.log("=== Print Number ====");
print(10);
console.log("=== Print Reverse Number ====");
printRev(10);
console.log("=== Sort an Array ===");
let arr = [4, 2, 1, 5, 3];
sort(arr);
console.log(arr);
console.log("=== Tower Of Honoi ===");
printSteps(3, 1, 2, 3);
console.log("=== Multiply an Array ===");
console.log(multiply(arr, arr.length));
console.log("=== Kth Symbol in Grammar ===");
console.log(generateGrammar(4, 6));
console.log("=== Sort a Stack ===");
let stack = new Stack();
stack.push(2);
stack.push(3);
stack.push(5);
stack.push(4);
stack.push(1);
sortStack(stack);
stack.printStack();
console.log("=== Reverse a Stack ===");
reverse(stack);
stack.printStack();
console.log("=== Remove Middle Element from Stack ===");
let k = Math.floor(stack.size() / 2 + 1);
deleteMiddle(stack, k);
stack.printStack();
console.log(" =*=*=*=*= IBH Method =*=*=*=*= ");
